[package]
name = "todo"
version = "0.1.0"
edition = "2021"

[dependencies]
hecs = { version = "0.10.5", features = ["macros"] }
macroquad = "0.4.11"
rapier2d = { version = "0.22.0" }

[profile.dev.package.rapier2d]
# opt-level = 3